<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.0" name="tiles" tilewidth="16" tileheight="16" tilecount="924" columns="33">
 <image source="tiles.png" width="528" height="448"/>
 <tile id="0" type="block1"/>
 <tile id="1" type="block2"/>
 <tile id="2" type="block3"/>
 <tile id="3" type="block4"/>
 <tile id="5" type="fence"/>
 <tile id="6" type="pulley_left"/>
 <tile id="7" type="horizontal_wire"/>
 <tile id="8" type="pulley_right"/>
 <tile id="11" type="castle1"/>
 <tile id="12" type="castle-window-left"/>
 <tile id="13" type="castle2"/>
 <tile id="14" type="castle-window-right"/>
 <tile id="24" type="question"/>
 <tile id="25" type="question"/>
 <tile id="26" type="question"/>
 <tile id="27" type="question"/>
 <tile id="33" type="block5"/>
 <tile id="36" type="bridge"/>
 <tile id="38" type="soil"/>
 <tile id="39" type="vertical_wire"/>
 <tile id="40" type="trunk"/>
 <tile id="44" type="castle3"/>
 <tile id="45" type="castle-arch"/>
 <tile id="46" type="castle-door"/>
 <tile id="66" type="block-underground-1"/>
 <tile id="67" type="block-underground-2"/>
 <tile id="68" type="block-underground-3"/>
 <tile id="69" type="block-underground-4"/>
 <tile id="99" type="block-underground-5"/>
 <tile id="232" type="block_green"/>
 <tile id="264" type="pipe-up-head-left"/>
 <tile id="265" type="pipe-up-head-right"/>
 <tile id="266" type="pipe-side-head-up"/>
 <tile id="267" type="pipe-side-body-up"/>
 <tile id="268" type="pipe-side-tail-up"/>
 <tile id="269" type="block_grass_1"/>
 <tile id="270" type="block_grass_2"/>
 <tile id="271" type="block_grass_3"/>
 <tile id="272" type="edge_moutain_left"/>
 <tile id="273" type="top_mountain"/>
 <tile id="274" type="edge_moutain_right"/>
 <tile id="277" type="bunch"/>
 <tile id="278" type="bunch_up"/>
 <tile id="279" type="handrail"/>
 <tile id="280" type="flag-1"/>
 <tile id="281" type="flag-2"/>
 <tile id="297" type="pipe-up-body-left"/>
 <tile id="298" type="pipe-up-body-right"/>
 <tile id="299" type="pipe-side-head-bottom"/>
 <tile id="300" type="pipe-side-body-bottom"/>
 <tile id="301" type="pipe-side-tail-bottom"/>
 <tile id="305" type="body_moutain_right"/>
 <tile id="306" type="body_moutain"/>
 <tile id="307" type="body_moutain_left"/>
 <tile id="310" type="grass3"/>
 <tile id="311" type="bunch_down"/>
 <tile id="313" type="flag-body-1"/>
 <tile id="347" type="flag-4"/>
 <tile id="413" type="flag-3"/>
 <tile id="462" type="pipe-up-head-left-light"/>
 <tile id="463" type="pipe-up-head-right-light"/>
 <tile id="475" type="bunch_light"/>
 <tile id="476" type="bunch_up_light"/>
 <tile id="477" type="handrail_light"/>
 <tile id="478" type="flag-dark-1"/>
 <tile id="495" type="pipe-up-body-left-light"/>
 <tile id="496" type="pipe-up-body-right-light"/>
 <tile id="509" type="bunch_down_light"/>
 <tile id="511" type="flag-body-light-1"/>
 <tile id="605" type="moss"/>
 <tile id="660" type="cloud1"/>
 <tile id="661" type="cloud2"/>
 <tile id="662" type="cloud3"/>
 <tile id="663" type="water_surface_2"/>
 <tile id="693" type="cloud4"/>
 <tile id="694" type="cloud5"/>
 <tile id="695" type="cloud6"/>
 <tile id="696" type="water2"/>
 <tile id="697" type="cloud_standing"/>
 <tile id="861" type="water_surface"/>
 <tile id="894" type="water"/>
</tileset>
