#pragma once
#include "Scenes/Home/HomeScene.h"
#include "Scenes/Exit/ExitScene.h"
#include "Scenes/Game/GameScene.h"
#include "Scenes/Login/LoginScene.h"
#include "Scenes/Setting/SettingScene.h"
#include "Scenes/Register/RegisterScene.h"
#include "Scenes/KeyBinding/KeyBindingScene.h"
#include "Scenes/Map/MapScene.h"